### ISSUE TITLE
Surface the Saves

### ISSUE THREAD

**Issue by bhwithun** [CalvinTheRed/RPGL#18]
As a Client
I want visibility to know if the target saves or fails against <i>something</i>
So that I can report it to the user

**Comment by CalvinTheRed** [comment]
You can now write your own subclass extending RPGLContext. When you do, you can override the viewCompletedSubevent() method in order to view the results of any arbitrary Subevent. You can use this method to inform the user when they fail a save by viewing the JSON content of the completed Subevent.

**Comment by bhwithun** [comment]
⛸️
